### ISSUE TITLE
worker timed out

### ISSUE THREAD

**Issue by DirkHeinke** [overleaf/spelling#2]
I activated spellcheck on a big file and the worker always times out after 4 seconds. So the only way to get spellchecking is to change every paragraph, so that the check is triggered again with less words. Is there a way to configure the timeout of 4 seconds, or, better, make the timeout controlled by the size of the input?

**Comment by jpallen** [comment]
It's not configurable at the moment, but you can edit the value in the code here: https://github.com/sharelatex/spelling-sharelatex/blob/master/app/coffee/ASpell.coffee#L92

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
