### ISSUE TITLE
Ignoring arguments in LaTeX commands

### ISSUE THREAD

**Issue by andrewfowlie** [overleaf/spelling#3]
I noticed sharelatex/sharelatex#76, which suggests that the spell checker should ignore arguments to common LaTeX commands, e.g.

```
\cite{DontCheckMe}
\label{DontCheckMe}
\ref{DontCheckMe}
```

Does the spell-checker just use aspell through a [pipe](http://aspell.net/man-html/Through-A-Pipe.html)? From the command line, aspell can ignore specified LaTeX commands, e.g. to ignore the arguments of the above commands,

```
aspell \
--mode=tex \
--master=en_GB-ise \
--add-tex-command='cite p' \
--add-tex-command='ref p' \
--add-tex-command='label p' \
check MY_FILE.tex
```

For details about the syntax, see 4.4.1.5 [here](http://aspell.net/0.50-doc/man-html/4_Customizing.html). This is a very simple way of achieving the desired result.

Can you set-up something similar in the aspell pipe in spelling-sharelatex?

**Comment by innisfree** [comment]
Browsing the code, couldn't it be quite simply added [here](https://github.com/sharelatex/spelling-sharelatex/blob/7467b409c35a463ddf6220547675e388e7eccc3e/app/coffee/ASpellWorker.coffee#L12):

    @pipe = child_process.spawn("aspell", ["pipe", "-t", "--encoding=utf-8", "-d", language])

Perhaps this could be changed to something like (though tidier):
    
    tex_commands  = ["cite p", "ref p", "label p"]
    aspell_commands = ["--add-tex-command=" + "'" + command + "'" for command in tex_commands]
    joined_apsell_commands = " ".join(aspell_commands)
    @pipe = child_process.spawn("aspell", ["pipe", "-t", "--encoding=utf-8", "-d",  joined_apsell_commands, language])

You can add in lots of `tex_commands` to ignore or load that list from a file etc.

**Comment by Philipp91** [comment]
Without this, the spell-checker is too annoying to actually turn on, and hence useless. So +1.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
