### ISSUE TITLE
Compillation fails: no type named 'GCEpilogueCallback' in 'v8::Isolate'

### ISSUE THREAD

**Issue by yurivict** [overleaf/spelling#5]
Overall sharelatex build (grunt command) fails in syntax with this error:

```
> v8-profiler@5.6.0 install /tmp/sharelatex/spelling/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

gmake: Entering directory '/tmp/sharelatex/spelling/node_modules/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
In file included from ../src/profiler.cc:2:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
```

I am in the process of creating the FreeBSD port for sharelatex, so suggestion to use docker won't work.

node-6.1.0
npm-3.8.8

**Comment by henryoswald** [comment]
I can't help much but can tell you some of the modules might break on node 6, most of our stuff is still 0.x

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
